version: "3"
services:
    worker_1:
      build:
        context: .
      image: julia-tdl
      networks:
        - backend
      hostname: worker_1
      volumes:
        - "./workdir:/home/montecarlo/workdir"

    worker_2:
      image: julia-tdl
      depends_on: 
        - worker_1
      networks:
        - backend
      hostname: worker_2
      volumes:
        - "./workdir:/home/montecarlo/workdir"

    worker_3:
      image: julia-tdl
      depends_on: 
        - worker_1
      networks:
        - backend
      hostname: worker_3
      volumes:
        - "./workdir:/home/montecarlo/workdir"

    worker_4:
      image: julia-tdl
      depends_on: 
        - worker_1
      networks:
        - backend
      hostname: worker_4
      volumes:
        - "./workdir:/home/montecarlo/workdir"

    lead:
      build:
        context: .
        dockerfile: Dockerfile_lead
      networks:
        - backend
      ports:
        - "2022:22"
        - "8088:8088"
      hostname: lead
      depends_on:
        - worker_1
        - worker_2
        - worker_3
        - worker_4
      volumes:
        - "./.ssh-lead:/root/.ssh"
        - "./.ssh-lead:/home/montecarlo/.ssh"
        - "./workdir:/home/montecarlo/workdir"
        
networks:
  backend:
